### ISSUE TITLE
Checking merge

### ISSUE THREAD

**Issue by bengalspice** [catherinestav/intro-data-capstone-musclehub#1]
https://github.com/catherinestav/intro-data-capstone-musclehub/blob/56a98881b639442893dceca7a4f7184a43775bde/MuscleHub_project/musclehub.py#L133

Good use of `len(df)` to check that you had the correct number of entries after the merge! Just for safety, it would have also been good to run df.head() to make sure that the columns merged properly as well.

**Comment by vrestles** [comment]
Tnak you! Will be using your tip for sure!
