### ISSUE TITLE
Extra code

### ISSUE THREAD

**Issue by bengalspice** [catherinestav/intro-data-capstone-musclehub#2]
https://github.com/catherinestav/intro-data-capstone-musclehub/blob/56a98881b639442893dceca7a4f7184a43775bde/MuscleHub_project/musclehub.py#L165-L174

These weren't required for analysis. If there is something interesting you discovered by running this, including it as a #comment would help the reader understand why this appears in the code.

**Comment by vrestles** [comment]
I just wanted to know time frame of the experiment. I mentioned it in the presentation.
