### ISSUE TITLE
Extra step

### ISSUE THREAD

**Issue by bengalspice** [catherinestav/intro-data-capstone-musclehub#3]
https://github.com/catherinestav/intro-data-capstone-musclehub/blob/56a98881b639442893dceca7a4f7184a43775bde/MuscleHub_project/musclehub.py#L190

If you created this just for the pie chart, you could have skipped over by just used email.values for the same effect.

**Comment by vrestles** [comment]
I did it just for better understanding of what values is going to be stored in this column.
