### ISSUE TITLE
Combine steps

### ISSUE THREAD

**Issue by bengalspice** [catherinestav/intro-data-capstone-musclehub#4]
https://github.com/catherinestav/intro-data-capstone-musclehub/blob/56a98881b639442893dceca7a4f7184a43775bde/MuscleHub_project/musclehub.py#L362-L368

To simplify things, these two lines could have been combined into one.

**Comment by vrestles** [comment]
Ok. I did it this way:
`just_apps = df[df['is_application'] == 'Application']`
