### ISSUE TITLE
Plotting bar graphs

### ISSUE THREAD

**Issue by bengalspice** [catherinestav/intro-data-capstone-musclehub#5]
https://github.com/catherinestav/intro-data-capstone-musclehub/blob/56a98881b639442893dceca7a4f7184a43775bde/MuscleHub_project/musclehub.py#L553-L561

Just for clarity, it's better to code for the bar graph before labeling the x- and y- axis.

**Comment by catherinestav** [comment]
plt.figure(figsize=(3,4))
ax = plt.subplot()

plt.bar(x_values,heights1,color=colors,width=0.5)

ax.set_yticklabels(y_labels)
for a,b in zip(x_values,heights1):
    plt.text(a,b+3,str(b)+'%',horizontalalignment='center',fontweight='bold')
plt.ylim(ymax=100)
plt.title('Percent of visitors who apply',y=1.1)

plt.show()

**Comment by vrestles** [comment]
Thank you. Got it!
I create a figure and a subplot first, then a bar and only after this I set tick labels, axis limits and title.
